### PR TITLE
fix(mmu): add missing constraint

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

**Review by lorenzogentile404 — COMMENTED** [review]
Can you paste the link to the Veridise issue?

**Comment by letypequividelespoubelles** [comment]
> Can you paste the link to the Veridise issue?
The link is in the issue already

**Review by lorenzogentile404 — COMMENTED** [review]
I cannot find where comment 4a is addressed.

**Review by lorenzogentile404 — APPROVED** [review]

**Comment by letypequividelespoubelles** [comment]
> I cannot find where Veridise issue 4a is addressed, the rest LGTM.

Nice catch. It's because it's a trash constraint, I left a comment in the Veridise audit

**Pull request merged**
